permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Coffee"
  description: |
    A small old coffee shop

  font_url: "https://use.typekit.net/arf3lvz.css"

  colors:
    background: "--color-secondary-light"
    accent: "--color-accent-light"
    patterns:
      brand.logos: "--color-primary-light"
  rationales:
    typefaces.primary: |
      asdfasdf
    typeface.secondary: |
      asdfff  asdf
