permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Coffee"
  description: |
    A small old coffee shop

  font_url: "https://use.typekit.net/gkk5zti.css"

  colors:
    background: "--color-accent"
    accent: "--color-accent-blue"
    patterns:
      brand.logos: "--color-accent-blue"
  rationales:
    typefaces.primary: |
      asdfasdf
    typeface.secondary: |
      asdfff  asdf
